const headers = {
  actions: "Actions",
  area: "Département",
  annee_plantation: "Année plantation",
  color: "Couleur",
  code_officiel_geographique: "Code officiel géographique",
  contract_name: "Contrat",
  created_at: "Créé le",
  description: "Description",
  distance_pieds: "Distance pieds",
  distance_rang: "Distance rang",
  email: "Email",
  end_date: "Date de fin",
  grape_type: "Cépage",
  holder: "Titulaire",
  invoicer: "Bailleur",
  invoicee: "Fermier",
  invoice_date: "Date de facture",
  lieu_dit: "Lieu-dit",
  name: "Nom",
  number: "Numéro",
  phone: "Téléphone",
  price: "Prix",
  quantity: "Quantité",
  reference_cadastrale: "Référence cadastrale",
  sex: "Nom de famille",
  start_date: "Date de début",
  source: "Source",
  supplier_id: "Fournisseur",
  surface: "Surface",
  tag_id: "Marqueur",
  total_amount: "Montant total",
  town: "Commune",
  type: "Type",
  unit: "Unité",
  updated_at: "Mis à jour le",
  year: "Année",
  payment_date: "Date",
  amount: "Montant",
  invoice_number: "Numéro de facture"
}

export { headers }